apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container
  name: multi-container
spec:
  containers:
  - image: busybox
    name: multi-container1
    command:
     - /bin/sh
    args:
     - -c
     - ls;  sleep 3600
  - image: busybox
    name: multi-container2
    command:
     - /bin/sh # we can just use args instead of specifying command as well
    args:
     - -c
     - echo "Hello World";  sleep 3600
  - image: busybox
    name: multi-container3
    command:
     - /bin/sh
    args:
     - -c
     - echo "this is the third container";  sleep 3600
       resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
