apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kustomization-example-
commonAnnotations:
  message: Hello, I am staging!
commonLabels:
  env: dev
  name: nginx
images:
  - name: nginx
    newName: nginx
    newTag: 1.16
resources:
- nginx.yaml
- nginx-svc.yaml
- nginx-configmap.yaml
