apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    name: "test-volumes"
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/vol
