apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bash
  name: bash
spec:
  containers:
  - args:
    - sleep
    - "8000"
    image: bash
    name: bash
    resources: {}
    envFrom:
     - configMapRef:
        name: drinks
    volumeMounts:
    - name: secret-vol
      mountPath: /tmp/secret1
  volumes:
  - name: secret-vol
    secret:
      secretName: secret1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
